screams = [
    ':-D',
    '1337!',
    'Alaaf!',
    'Allememaggies!',
    'Allez zunne!',
    'Amai!',
    'Amazing!',
    'Awesome!',
    'Badass!',
    'Bam!',
    'Bang!',
    'Beautiful!',
    'Boem!',
    'Boom!',
    'Booyakasha!',
    'Brilliant!',
    'Bring it on!',
    'But seriously!',
    'C\'est incroyable!',
    'Congratulations!',
    'Cool!',
    'Cowabunga!',
    'Crazy!',
    'Cute!',
    'Dance!',
    'Delicious!',
    'Duizend bommen en granaten!',
    'Epic!',
    'Excellent!',
    'Fab!',
    'Fabulous!',
    'Fantabulous!',
    'Fantastic!',
    'Fantastical!',
    'Fantastigeweldiprachtig!',
    'Formidable!',
    'Fun fun fun!',
    'Gaaf!',
    'Gefeliciteerd!',
    'Get up your shirts!',
    'Geweldig!',
    'Gezondheid!',
    'Give it to me baby!',
    'Go ahead. Make my day.',
    'Go crazy!',
    'Good!',
    'Gorgeous!',
    'Great!',
    'Gut gemacht, Junge!',
    'Hasta la pasta!',
    'Hatseflats!',
    'Here we go!',
    'Hendig kicks of wat hey!',
    'Hieperdepiep hoera!',
    'Hoe cool is dat?!',
    'Hoei!',
    'Holy moly!',
    'Hoppa!',
    'Hot!',
    'https://goo.gl/SsAhv',
    'Hupsakee!',
    'I love the smell of led strips in the morning!',
    'Ik zal eens iets zeggen he:',
    'In your face!',
    'Incredible!',
    'It\'s a small step for men...',
    'It\'s alive!',
    'It\'s life, Jim. But not as we know it!',
    'Ja!',
    'Joepie!',
    'Jump!',
    'Kanonne!',
    'Keep calm and command TinkerLicht!',
    'Kicken!',
    'Knal!',
    'Lo and behold!',
    'LOL!',
    'Lumos!',
    'Lumos Maxima!',
    'Magical!',
    'Man, man, man!',
    'Marvelous!',
    'May the force be with you!',
    'May you be touched by his noodly appendage!',
    'Monstrous!',
    'Mooi hoor!',
    'Nee, echt!',
    'Nee maar!',
    'Nice!',
    'Oh joy!',
    'Oh la la!',
    'Oh now you\'ve done it!',
    'Omdat het kan!',
    'OMG!',
    'OMGWTFBBQ!',
    'Ongelofeloos!',
    'Ongelofelijk!',
    'Oooh!',
    'Pats!',
    'Perfect!',
    'Prachtig allemachtig!',
    'Pretty!',
    'Proost!',
    'Put your hands up in the air!',
    'Rad!',
    'Retteketet!',
    'Right on!',
    'ROFL!',
    'Sapperloot!',
    'Scream in awe!',
    'Scream in extacy!',
    'Super!',
    'Superb!',
    'Supercalifragilisticexpialidocious!',
    'Sexy!',
    'Sick!',
    'Sing!',
    'Slick!',
    'Spread the word!',
    'Stoer!',
    'Stop. Hammertime!',
    'Subzerocool!',
    'Superb!',
    'Sweet!',
    'Tadaa!',
    'Terrific!',
    'Thank you!',
    'Tien op tien',
    'Tjakkaaa!',
    'Vet!',
    'Vette shizzle!',
    'W00t!',
    'Wakkabakkaboe!',
    'Wat een baas!',
    'Wat een held!',
    'Wat doe je met me?!',
    'Wat zeg je me daar van!',
    'Way to go!',
    'Weehoo!',
    'Well done!',
    'Wham, bam, thank you ma\'m!',
    'Whop!',
    'Wiehoe!',
    'Wicked!',
    'Wonderful!',
    'Wow!',
    'Wunderbar!',
    'Yaa-hoo!',
    'Ya man!',
    'Yay!',
    'Yell!',
    'Yesss!',
    'Yeehaa!',
    'Yippee-ki-yay!',
    'Yo!',
    'YOLO!',
    'You did it!',
    'Zo hey!',
    'Zo zo!',
    'Zonne grote vuurbal jonguh! BAM!']
