screams = [
    ':-D',
    '1337!',
    'Allememaggies!',
    'Amai!',
    'Amazing!',
    'Awesome!',
    'Badass!',
    'Bam!',
    'Bang!',
    'Beautiful!',
    'Booyakasha!',
    'Brilliant!',
    'Bring it on!',
    'Call in the Calvary, eh... Calvados!',
    'Cool!',
    'Cowabunga!',
    'Crazy!',
    'Cute!',
    'Dance!',
    'Delicious!',
    'Duizend bommen en granaten!',
    'Epic!',
    'Excellent!',
    'Fab!',
    'Fabulous',
    'Fantabulous!',
    'Fantastic!',
    'Fantastical!',
    'Formidable!',
    'Fun fun fun!',
    'Gaaf!',
    'Get up your shirts!',
    'Geweldig!',
    'Go crazy!',
    'Good!',
    'Gorgeous!',
    'Great!',
    'Hatseflats!',
    'Here we go!',
    'Hendig kicks of wat hey!',
    'Hieperdepiep hoera!',
    'Hoe cool is dat?!',
    'Hoei!',
    'Holy moly!',
    'Hoppa!',
    'Hot!',
    'Hupsakee!',
    'In your face!',
    'Incredible!',
    'It\'s alive!',
    'Allez zunne!',
    'Jump!',
    'Kicken!',
    'Lo and behold!',
    'Lol!',
    'Lumos!',
    'Lumos Maxima!',
    'Magical!',
    'Man, man, man!',
    'Marvelous!',
    'Mooi hoor!',
    'Nee, echt!',
    'Nice!',
    'Oh joy!',
    'Omdat het kan!',
    'OMG!',
    'OMGWTFBBQ',
    'Ongelofeloos!',
    'Ongelofelijk!',
    'Oooh!',
    'Perfect!',
    'Prachtig allemachtig!',
    'Pretty!',
    'Sapperloot!',
    'Scream in awe!',
    'Scream in extacy!',
    'Super!',
    'Supercalifragilisticexpialidocious!',
    'Rad!',
    'Sexy!',
    'Sick!',
    'Sing!',
    'Slick!',
    'Spread the word!',
    'Stoer!',
    'Stop. Hammertime!',
    'Superb!',
    'Sweet!',
    'Tadaa!',
    'Terrific!',
    'Vet!',
    'Vette shizzle!',
    'W00t!',
    'Wakkabakkaboe!',
    'Wat een baas!',
    'Wat doe je met me?!',
    'Wat zeg je me daar van!',
    'Way to go!',
    'Weehoo!',
    'Well done!',
    'Wham, bam, thank you ma\'m!',
    'Whop!',
    'Wiehoe!',
    'Wicked!',
    'Wonderful!',
    'Wow!',
    'Wunderbar!',
    'Yaa-hoo!',
    'Ya man!',
    'Yay!',
    'Yell!',
    'Yesss!',
    'Yeehaa!',
    'Yo!',
    'You did it!',
    'Zo hey!']
