screams = [
    ':-D',
    '1337!',
    '3... 2... 1... Liftoff!',
    'A je to, Buurman!',
    'Alaaf!',
    'Allememaggies!',
    'Allez zunne!',
    'Amai!',
    'Amazing!',
    'Awesome!',
    'Badass!',
    'Bam!',
    'Bang!',
    'Beautiful!',
    'Boem!',
    'Boks!',
    'Boom!',
    'Booyakasha!',
    'Brilliant!',
    'Bring it on!',
    'But seriously!',
    'C\'est incroyable!',
    'Can you handle it?',
    'Chique!',
    'Congratulations!',
    'Cool!',
    'Cowabunga!',
    'Crazy!',
    'Cute!',
    'Daar gaan we!',
    'Dance!',
    'Delicious!',
    'Dit kan toch niet waar zijn!',
    'Doe dat maar eens na!',
    'Duizend bommen en granaten!',
    'En er was licht!',
    'Epic!',
    'Excellent!',
    'Fab!',
    'Fabulous!',
    'Fantabulous!',
    'Fantastic!',
    'Fantastical!',
    'Fantastigeweldiprachtig!',
    'Flabbergasted!',
    'Formidable!',
    'Fun fun fun!',
    'Gaaf!',
    'Geen paniek!',
    'Gefeliciteerd!',
    'Get up your shirts!',
    'Geweldig!',
    'Gezondheid!',
    'Give it to me baby!',
    'Go ahead. Make my day.',
    'Go crazy!',
    'Godnondeju!',
    'Goeie grutten!',
    'Goeiedag zeg!',
    'Good!',
    'Gorgeous!',
    'Great!',
    'Gut gemacht, Junge!',
    'Hasta la pasta!',
    'Hatseflats!',
    'Here we go!',
    'Hendig kicks of wat hey!',
    'Het is echt zo!',
    'Hieperdepiep hoera!',
    'High five!',
    'Hoe cool is dat?!',
    'Hoei!',
    'Holy moly!',
    'Hoppa!',
    'Hot!',
    'https://goo.gl/SsAhv',
    'Hupsakee!',
    'I love it when a plan comes together!',
    'I love the smell of led strips in the morning!',
    'Ich flipp aus!',
    'Ik zal eens iets zeggen he:',
    'In your face!',
    'Incredible!',
    'It\'s a small step for men...',
    'It\'s alive!',
    'It\'s life, Jim. But not as we know it!',
    'Ja!',
    'Joepie!',
    'Jump!',
    'Kanonne!',
    'Kedeng!',
    'Keep calm and command TinkerLicht!',
    'Kicken!',
    'Kicks!',
    'Knal!',
    'Komtie!',
    'Lo and behold!',
    'LOL!',
    'Lumos!',
    'Lumos Maxima!',
    'Magical!',
    'Man, man, man!',
    'Marvelous!',
    'May the force be with you!',
    'May you be touched by his noodly appendage!',
    'Monstrous!',
    'Mooi hoor!',
    'Nee, echt!',
    'Nee maar!',
    'Nice!',
    'Oh joy!',
    'Oh la la!',
    'Oh now you\'ve done it!',
    'Omdat het kan!',
    'OMG!',
    'OMGWTFBBQ!',
    'Ongelofeloos!',
    'Ongelofelijk!',
    'Oooh!',
    'Pats!',
    'Peace!',
    'Perfect!',
    'Plopperdeplopperdeplop!',
    'Prachtig allemachtig!',
    'Pretty!',
    'Proost!',
    'Put your hands up in the air!',
    'Rad!',
    'Retteketet!',
    'Right on!',
    'ROFL!',
    'Roflcopter!',
    'Sapperloot!',
    'Scoobeedoobeedoo!',
    'Scream in awe!',
    'Scream in extacy!',
    'Sexy!',
    'Sick!',
    'Sing!',
    'Sjiek!',
    'Slick!',
    'Spread the word!',
    'Stoer!',
    'Stop. Hammertime!',
    'Subzerocool!',
    'Superb!',
    'Super!',
    'Superb!',
    'Supercalifragilisticexpialidocious!',
    'Sweet!',
    'Tadaa!',
    'Tasteful!',
    'Te gek!',
    'Terrific!',
    'Thank you!',
    'Tien op tien!',
    'Tja!',
    'Tjakkaaa!',
    'Vet!',
    'Vette shizzle!',
    'W00t!',
    'Waar is dat feestje?!',
    'Wakkabakkaboe!',
    'Wat een baas!',
    'Wat een held!',
    'Wat doe je met me?!',
    'Wat zeg je me daar van!',
    'Way to go!',
    'Weehoo!',
    'Well done!',
    'Wham, bam, thank you ma\'m!',
    'Whop!',
    'Wie wil dat nou niet?',
    'Wiehoe!',
    'Wicked!',
    'Wonderful!',
    'Wow!',
    'Wunderbar!',
    'Yaa-hoo!',
    'Ya man!',
    'Yay!',
    'Yell!',
    'Yesss!',
    'Yeehaa!',
    'Yippee-ki-yay!',
    'Yo!',
    'YOLO!',
    'You did it!',
    'Zo hey!',
    'Zo zo!',
    'Zonne grote vuurbal jonguh! BAM!']
